### ISSUE TITLE
troubles with loading

### ISSUE THREAD

**Issue by Serjoga80** [hfshr/distill_blog#2]
Hi Harry,

for some reasons I get next message when try to download data with your package:

"Error in str_match(css, el_re) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/stringi/R/stringi.rdb' is corrupt
In addition: Warning messages:
1: In str_match(css, el_re) : restarting interrupted promise evaluation
2: In str_match(css, el_re) : internal error -3 in R_decompress1

Could you please be so kind and assist me with solving this problem?

**Comment by hfshr** [comment]
Hey @Serjoga80, Looks like it might be an issue with the stringi / stringr pakcage. Usually with an error like that I'll try removing / reinstalling the package and/or restarting R.  

What data were you trying to download out of interest?

**Comment by Serjoga80** [comment]
The problem was in my old version of R needed an upgrade. I managed to solve it and download your package with all necessary accessories, but for some reason still get problems when try to run your example code:

> me <- get_athlete(fn = "Harry", sn = "Fisher", club = "Cardiff/Cardiff Met Uni") %>% 
+   select(event, perf, pos, venue, date) 
Error in get_athlete(fn = "Harry", sn = "Fisher", club = "Cardiff/Cardiff Met Uni") : 
  could not find function "get_athlete"


Any suggestions? I have several ideas on analysis of data performances, but firstly wish to learn how to download the data from the webpage. Your package seems very interesting, if I can only download it :)

**Comment by hfshr** [comment]
Sill question, did you run `library(poweRof10)` before calling the function? Running the following code works for me:

```
remotes::install_github("hfshr/poweRof10") #only need to run once
library(poweRof10)
library(tidyverse)

me <- get_athlete(fn = "Harry", sn = "Fisher", club = "Cardiff/Cardiff Met Uni") %>% 
  select(event, perf, pos, venue, date) 
```

I should warn you there may be a few issues with the package as I didn't put too much time into it... If you do find any issues feel free to open them here: https://github.com/hfshr/poweRof10/issues

**Comment by Serjoga80** [comment]
Excellent! I got it! Start learning it :) Thanks for your input. I will get back to, if I have any additional question and once ready for discussion and questions  to be answered by the data :)

**Comment by hfshr** [comment]
Great! I'll close this issue, but feel free to open another if you run into any other problems.
